export const ALBUMS = [
    {
        id: 0,
        name: 'Baby',
        image: require('../img/Baby/baby-home.jpg'),
        count: 3,
        date: 'July 2018',
        featured: true,
    },
    {
        id: 1,
        name: 'Family',
        image: require('../img/Family/family-home.jpg'),
        count: 3,
        date: 'February 2019',
        featured: false,
    },
    {
        id: 2,
        name: 'Maternity',
        image: require('../img/Maternity/maternity-home.jpg'),
        count: 3,
        date: 'March 2021',
        featured: false,
    },
    {
        id: 3,
        name: 'Events',
        image: require('../img/Events/events-1.jpg'),
        count: 3,
        date: 'July 2018',
        featured: true,
    },
    {
        id: 4,
        name: 'Portraits',
        image: require('../img/Portraits/portraits-1.jpg'),
        count: 3,
        date: 'February 2019',
        featured: false,
    },
    {
        id: 5,
        name: 'Travel',
        image: require('../img/Travel/travel-1.jpg'),
        count: 3,
        date: 'March 2021',
        featured: false,
    }
];